CREATE
SEQUENCE IF NOT EXISTS book_seq START
WITH 1 INCREMENT BY 50;

ALTER TABLE book
    ALTER COLUMN author DROP NOT NULL;

ALTER TABLE contact_messages
    ALTER COLUMN email DROP NOT NULL;

ALTER TABLE book
    ALTER COLUMN genre DROP NOT NULL;

ALTER TABLE contact_messages
    ALTER COLUMN phone TYPE VARCHAR (255) USING (phone:: VARCHAR (255));

ALTER TABLE book
    ALTER COLUMN title DROP NOT NULL;